### ISSUE TITLE
Model download always fails halfway

### ISSUE THREAD

**Issue by holmofy** [Anush008/fastembed-rs#136]
```rust
let cache_dir = hf_config.cache_dir;
let text_embedding = TextEmbedding::try_new(
    InitOptions::new(EmbeddingModel::ParaphraseMLMpnetBaseV2)
        .with_show_download_progress(true)
        .with_cache_dir(
            format!("{cache_dir}/sentence-transformers/paraphrase-mpnet-base-v2").into(),
        ),
)
.expect("text embedding init failed");
```
The error is as follows: 
```sh
thread 'main' panicked at dtiku-backend/src/plugins/fastembed.rs:32:10:
text embedding init failed: Failed to retrieve onnx/model.onnx

Caused by:
    0: I/O error peer closed connection without sending TLS close_notify: https://docs.rs/rustls/latest/rustls/manual/_03_howto/index.html#unexpected-eof
    1: peer closed connection without sending TLS close_notify: https://docs.rs/rustls/latest/rustls/manual/_03_howto/index.html#unexpected-eof

Stack backtrace:
   0: <E as anyhow::context::ext::StdError>::ext_context
             at /home/holmofy/.cargo/registry/src/index.crates.io-6f17d22bba15001f/anyhow-1.0.93/src/backtrace.rs:27:14
   1: anyhow::context::<impl anyhow::Context<T,E> for core::result::Result<T,E>>::context
             at /home/holmofy/.cargo/registry/src/index.crates.io-6f17d22bba15001f/anyhow-1.0.93/src/context.rs:54:31
   2: fastembed::text_embedding::impl::<impl fastembed::text_embedding::init::TextEmbedding>::try_new
             at /home/holmofy/.cargo/git/checkouts/fastembed-rs-49d7d93c2ae16498/83fb118/src/text_embedding/impl.rs:65:36
   3: <backend::plugins::fastembed::EmbeddingPlugin as spring::plugin::Plugin>::build::{{closure}}
             at ./src/plugins/fastembed.rs:25:30
   4: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/core/src/future/future.rs:123:9
   5: spring::app::AppBuilder::build_plugins::{{closure}}
             at /home/holmofy/.cargo/registry/src/index.crates.io-6f17d22bba15001f/spring-0.3.0/src/app.rs:241:40
   6: spring::app::AppBuilder::build::{{closure}}
             at /home/holmofy/.cargo/registry/src/index.crates.io-6f17d22bba15001f/spring-0.3.0/src/app.rs:209:30
   7: backend::main::{{closure}}
             at ./src/main.rs:29:10
   8: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/core/src/future/future.rs:123:9
   9: tokio::runtime::park::CachedParkThread::block_on::{{closure}}
             at /home/holmofy/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.41.1/src/runtime/park.rs:281:63
  10: tokio::runtime::coop::with_budget
             at /home/holmofy/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.41.1/src/runtime/coop.rs:107:5
  11: tokio::runtime::coop::budget
             at /home/holmofy/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.41.1/src/runtime/coop.rs:73:5
  12: tokio::runtime::park::CachedParkThread::block_on
             at /home/holmofy/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.41.1/src/runtime/park.rs:281:31
  13: tokio::runtime::context::blocking::BlockingRegionGuard::block_on
             at /home/holmofy/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.41.1/src/runtime/context/blocking.rs:66:9
  14: tokio::runtime::scheduler::multi_thread::MultiThread::block_on::{{closure}}
             at /home/holmofy/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.41.1/src/runtime/scheduler/multi_thread/mod.rs:87:13
  15: tokio::runtime::context::runtime::enter_runtime
             at /home/holmofy/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.41.1/src/runtime/context/runtime.rs:65:16
  16: tokio::runtime::scheduler::multi_thread::MultiThread::block_on
             at /home/holmofy/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.41.1/src/runtime/scheduler/multi_thread/mod.rs:86:9
  17: tokio::runtime::runtime::Runtime::block_on_inner
             at /home/holmofy/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.41.1/src/runtime/runtime.rs:370:45
  18: tokio::runtime::runtime::Runtime::block_on
             at /home/holmofy/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.41.1/src/runtime/runtime.rs:340:13
  19: backend::main
             at ./src/main.rs:31:5
  20: core::ops::function::FnOnce::call_once
             at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/core/src/ops/function.rs:250:5
  21: std::sys_common::backtrace::__rust_begin_short_backtrace
             at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/std/src/sys_common/backtrace.rs:155:18
  22: std::rt::lang_start::{{closure}}
             at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/std/src/rt.rs:159:18
  23: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once
             at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/core/src/ops/function.rs:284:13
  24: std::panicking::try::do_call
             at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/std/src/panicking.rs:559:40
  25: std::panicking::try
             at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/std/src/panicking.rs:523:19
  26: std::panic::catch_unwind
             at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/std/src/panic.rs:149:14
  27: std::rt::lang_start_internal::{{closure}}
             at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/std/src/rt.rs:141:48
  28: std::panicking::try::do_call
             at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/std/src/panicking.rs:559:40
  29: std::panicking::try
             at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/std/src/panicking.rs:523:19
  30: std::panic::catch_unwind
             at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/std/src/panic.rs:149:14
  31: std::rt::lang_start_internal
             at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/std/src/rt.rs:141:20
  32: std::rt::lang_start
             at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/std/src/rt.rs:158:17
  33: main
  34: <unknown>
  35: __libc_start_main
  36: _start
stack backtrace:
   0: rust_begin_unwind
             at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/std/src/panicking.rs:652:5
   1: core::panicking::panic_fmt
             at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/core/src/panicking.rs:72:14
   2: core::result::unwrap_failed
             at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/core/src/result.rs:1679:5
   3: core::result::Result<T,E>::expect
             at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/core/src/result.rs:1059:23
   4: <backend::plugins::fastembed::EmbeddingPlugin as spring::plugin::Plugin>::build::{{closure}}
             at ./src/plugins/fastembed.rs:25:30
   5: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/core/src/future/future.rs:123:9
   6: spring::app::AppBuilder::build_plugins::{{closure}}
             at /home/holmofy/.cargo/registry/src/index.crates.io-6f17d22bba15001f/spring-0.3.0/src/app.rs:241:40
   7: spring::app::AppBuilder::build::{{closure}}
             at /home/holmofy/.cargo/registry/src/index.crates.io-6f17d22bba15001f/spring-0.3.0/src/app.rs:209:30
   8: backend::main::{{closure}}
             at ./src/main.rs:29:10
   9: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/core/src/future/future.rs:123:9
  10: tokio::runtime::park::CachedParkThread::block_on::{{closure}}
             at /home/holmofy/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.41.1/src/runtime/park.rs:281:63
  11: tokio::runtime::coop::with_budget
             at /home/holmofy/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.41.1/src/runtime/coop.rs:107:5
  12: tokio::runtime::coop::budget
             at /home/holmofy/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.41.1/src/runtime/coop.rs:73:5
  13: tokio::runtime::park::CachedParkThread::block_on
             at /home/holmofy/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.41.1/src/runtime/park.rs:281:31
  14: tokio::runtime::context::blocking::BlockingRegionGuard::block_on
             at /home/holmofy/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.41.1/src/runtime/context/blocking.rs:66:9
  15: tokio::runtime::scheduler::multi_thread::MultiThread::block_on::{{closure}}
             at /home/holmofy/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.41.1/src/runtime/scheduler/multi_thread/mod.rs:87:13
  16: tokio::runtime::context::runtime::enter_runtime
             at /home/holmofy/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.41.1/src/runtime/context/runtime.rs:65:16
  17: tokio::runtime::scheduler::multi_thread::MultiThread::block_on
             at /home/holmofy/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.41.1/src/runtime/scheduler/multi_thread/mod.rs:86:9
  18: tokio::runtime::runtime::Runtime::block_on_inner
             at /home/holmofy/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.41.1/src/runtime/runtime.rs:370:45
  19: tokio::runtime::runtime::Runtime::block_on
             at /home/holmofy/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.41.1/src/runtime/runtime.rs:340:13
  20: backend::main
             at ./src/main.rs:31:5
  21: core::ops::function::FnOnce::call_once
             at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by Anush008** [comment]
Could this be a network issues?

**Comment by holmofy** [comment]
It always fails when it is downloaded to about 40%.

发自我的iPhone

**Comment by Anush008** [comment]
Can you check with a different model?

**Comment by holmofy** [comment]
It's a problem with the model. I changed to Resnet50 and it's ok.
```rust      
let image_embedding = ImageEmbedding::try_new(
      ImageInitOptions::new(ImageEmbeddingModel::Resnet50)
          .with_show_download_progress(true)
          .with_cache_dir(format!("{cache_dir}/Qdrant/resnet50-onnx").into()),
  )
  .expect("image embedding init failed");
```

**Comment by holmofy** [comment]
There is a problem with this ParaphraseMLMpnetBaseV2 model. I plan to use ParaphraseMLMiniLML12V2Q.
